Dev
Anastasia-Slesarenko/CBIR pull request #1
Opened 2024-05-22 09:24 UTC by Anastasia-Slesarenko

2024-05-31 11:08 UTC, avito-ds commented
" Решение задачи предоставлено в виде сервиса в который можно отправлять запросы (например из postman) или из браузера. Решение должно быть доступно во внешнем интернете. Оценивается бинарно, только 0 или 5."

Давай добавим postman-коллекцию с хендлерами, чтобы можно было легко протестировать. Пока не вижу где вообще описание ручки и ее вызовы

2024-05-31 11:08 UTC, avito-ds commented
Продумай, что должно быть на вход ручки, например, бинарник картинки или что. Подергай сама из постмана

2024-05-31 11:28 UTC, avito-ds requested changes

2024-05-31 11:28 UTC, avito-ds commented on demo_load_test.ipynb
хорошо, что есть тест нагрузки. Надо подумать как сделать, чтобы укладываться в 1 сек. Вроде бы такое ограничение закладывалось

2024-05-31 11:28 UTC, avito-ds commented on demo_load_test.ipynb
хорошо бы когда делаешь запросы в сервис юзать aiohttp и делать это асинхронно (через await). В твоем случае если поднят один инстанс синхронного сервера, это не даст прироста (если только нет батчирования). Но в общем случае все таки работает много подов сервиса и есть смысл кидать следующий запрос, не дожидаясь ответа предыдущего.

2024-05-31 11:28 UTC, avito-ds commented on demo_load_test.ipynb
ручку в итоге нужно будет сделать общедоступной, а не на локалхост

2024-05-31 11:28 UTC, avito-ds commented on README.md
> +pip install -r requirements-dev.txt
requirements-dev.txt должны ставиться при билде docker-compose-dev.yml и здесь лишние

2024-05-31 11:28 UTC, avito-ds commented on README.md
> +## Требования
это не надо писать. Требования не надо документировать, нужно делать нужную среду докером, чтобы пользователь не думал об этом

2024-05-31 11:28 UTC, avito-ds commented on Dockerfile
> +FROM python:3.11-slim
будет ли это работать после того как докер ввел санкции? Ты нашла обход? Мб зеркало какое?

2024-05-31 11:28 UTC, avito-ds commented on app.py
весь пайтон код нужный чтобы запустить сервис должен лежать в lib или в bin. В данном случае большинство файлов .py должно перекочевать в lib, а в bin файл который стартует сервис. И не бойся ввести папки внутри lib с понятными названиями, которые группируют эти файлы

2024-05-31 11:40 UTC, avito-ds commented
можешь еще скинуть ссылку на код-стайл курса по python?

2024-05-31 15:05 UTC, avito-ds requested changes

2024-05-31 15:05 UTC, avito-ds commented on app.py
> +@app.get("/train_faiss")
зачем делать ручку на train_faiss? Для регулярного переобучения?

2024-05-31 15:05 UTC, avito-ds commented on app.py
> +        candidates = get_similary_images(query_feature, topk=8)
а есть такое слово similary? Мне кажется, что просто similar должно быть

2024-05-31 15:05 UTC, avito-ds commented on app.py
> +):
если ты делаешь аннотации, может тогда писать и возвращаемый тип

2024-05-31 15:05 UTC, avito-ds commented on app.py
> +        html_data = {
давай отщепим из этой функции логику формирования html в отдельную функцию

2024-05-31 15:05 UTC, avito-ds commented on app.py
> +def create_and_insert_pg(
ты даешь название с точки зрения инструмента (pg) , а не функции. А нужно наоборот. Вот ты делаешь create и insert pg. Ты это зачем делаешь? Название должно ответить на этот вопрос. Если оно не ответило, то аннотация дополнительно прояснить

2024-05-31 15:05 UTC, avito-ds commented on app.py
> +    data: UploadFile = File(...),
и точно ли нужно это делать через ручку, если это что-то долгое как заливка базы? Обычно ручки нужны для каких-то онлайн (интерактивных) взаимодействий

2024-05-31 15:05 UTC, avito-ds commented on db.py
> +from typing import Generator
через какие линтеры ты прогоняла код? Обычно такие штуки требуют алфавитной сортировки импортов. Стоит прогонять

2024-05-31 15:05 UTC, avito-ds commented on db.py
> +        with connection.cursor() as cursor:
не очень хорошо, что у тебя в каждой функции создается свой connection. pg не очень любит такое. Лучше создавать класс Storage с этими методами (твои функции-запросы) внутри которого есть метод взять connection из пула. И пока объект этого класса живет он поддерживает постоянным число соединений в пуле

2024-05-31 15:05 UTC, avito-ds commented on db.py
> +            LIMIT 1 offset {idx}
почему не ввести image_id по которому завести индекс и искать через where image_id={image_id} или image_id in (список image_id). Я не уверен что решение через liimit offset работает быстро, выглядит костыльно как-то

2024-06-01 12:37 UTC, Anastasia-Slesarenko commented on app.py
> +    data: UploadFile = File(...),
В критериях указано:
"_У жюри должна быть возможность воспроизвести запуск сервиса на любом сервере:_
* _Клон кода (0.5 балла)_
* _Билд контейнера (0.5 балла)_
* _Запуск сервиса внутри контейнера (2 балла)_
* _Отправка примера запроса получен ответ с кодом 200. (2 балла)_ "

Для того, чтобы сервис отдавал похожие картинки после билда, нужно, чтобы в базе были данные, у faiss были индексы и где-то лежала моделька. Я не знала, как лучше это организовать. Поэтому сделала ручку, с помощью которой можно инициализировать заполнение базы и еще ручку для faiss. И думала сама ее использовать, когда будут запускать сервис на вм. А моделька при этом подтягивается с гугл-диска при первом запуске.

Подскажи, пожалуйста, как это тогда можно лучше организовать? 
(Если оставлять эти ручки, то надо еще в инструкцию это добавить).

2024-06-03 00:25 UTC, Anastasia-Slesarenko commented on Dockerfile
> +FROM python:3.11-slim
Да, работает через зеркало

2024-06-03 10:00 UTC, avito-ds commented on app.py
> +    data: UploadFile = File(...),
> нужно, чтобы в базе были данные, у faiss были индексы и где-то лежала моделька. Я не знала, как лучше это организовать.

это можно сделать отдельными скриптами. Ручки на это не нужны, так как ручки - это интерфейс для клиентов. А перечисленные действия делает оунер сервиса. И он может это даже руками как-то делать (например добавить данных в базу). Но если для всего его действий есть скрипты это лучше с точки зрения воспроизводимости. 

Вот если бы у тебя был отдельный сервис для переобучения, то можно было бы рассмотреть вариант сделать ручку, которая стартует переобучение. Но это за пределами требований к проекту

2024-06-06 15:49 UTC, budylinr requested changes

2024-06-06 15:49 UTC, budylinr commented on tests/gallery_images_test/1.jpg
давай уберем эти файлы из репозитория. Переложим в гугл диск или что-то подобное. В репе проекта не очень хорошо хранить:
- много нетекстовых файлов
- файлы большого размера (для этого Git LFS)
Если бы тут было 2 картинки, то ок, а 20 перебор.

2024-06-06 15:49 UTC, budylinr commented on Dockerfile
> +EXPOSE 8000
можно в Dockerfile не открывать порты, достаточно в docker-compose это делать

2024-06-06 15:49 UTC, budylinr commented on Dockerfile
> +# RUN mkdir /app
закоменченный код лучше удалять. Если у тебя какое-то опциональное поведение, например, в разных средах DEV, PROD разная среда, то предпочтительно это делать через переменные окружения.

2024-06-06 15:49 UTC, budylinr commented on FastAPI.postman_collection.json
не получилось успешно дернуть ручку :( Error: Invalid URI "http:///158.160.64.37/find_simular_images"
поправь variable, подними сервис

2024-06-06 15:49 UTC, budylinr commented on FastAPI.postman_collection.json
помнишь мы с тобой говорили, что хорошо бы сделать отдельную ручку, которая на выход дает не превью в html, а просто список фоток (можно просто список их айди или урлов).

2024-06-06 15:49 UTC, budylinr commented on FastAPI.postman_collection.json
всегда очень удобно при работе с картинками делать ручку, которая на вход принимает урл. Так проще найти примеров

2024-06-06 15:49 UTC, budylinr commented on docker-compose.yml
> +      - MODEL_URL="https://disk.yandex.ru/d/K7ozxAlGlPanlw"
лучше не светить на гитхабе конкретными урлами, это не секьюрно. Такие вещи лучше добавлять через environment переменные.

2024-06-06 15:49 UTC, budylinr commented on demo/demo_load.py
> +            "http://158.160.64.37/find_simular_images",
лучше не светить на гитхабе конкретными урлами, это не секьюрно. Такие вещи лучше добавлять через environment переменные.

2024-06-06 15:49 UTC, budylinr commented on lib/settings.py
> +MODEL_URL = "https://disk.yandex.ru/d/6U7YaqjrqGDjYQ"
не секьюрно. Можно завести .env файл, который ты раздашь проверяющим

2024-06-06 15:49 UTC, budylinr commented on lib/app.py
> +def find_simular_images(
опечатка simUlar

2024-06-06 15:49 UTC, budylinr commented on lib/app.py
> +        )
добавить бы еще ручку которая по урлу работает и ту, которая выдает только урлы или айди картинок

2024-06-06 15:49 UTC, budylinr commented on lib/utils.py
> +    file: int,
странно называть инт файлом

2024-06-06 15:49 UTC, budylinr commented on lib/utils.py
> +def get_bytes_image(
может в названии добавить что тут смысл в переформатировании в png, типа get_png_bytes

2024-06-06 15:49 UTC, budylinr commented on lib/utils.py
> +def load_torch_model(
из-за load кажется, что будут сохранять в оперативку, а не на жесткий диск. мб download ?

2024-06-06 15:49 UTC, budylinr commented on load_artifacts/requirements.txt
обычно requirements во внешней папке

2024-06-06 15:49 UTC, budylinr commented on load_artifacts/setup.sh
> +pip install torch==2.0.0+cu117 -f https://download.pytorch.org/whl/torch_stable.html
зачем setup.sh если есть Dockerfile?

2024-06-06 15:49 UTC, budylinr commented on load_artifacts/start.py
> +
обычно линтеры просят тут вставлять 2 строчки. Ты прогоняла каким-то линтером?

2024-06-06 15:49 UTC, budylinr commented on load_artifacts/utils.py
> +    storage.create_tables_structure()
мы при каждом старте заново создаем схему базы или только один раз при развертывании?

2024-06-06 15:49 UTC, budylinr commented on main.py
> +    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")
номер порта лучше брать из переменной окружения и синхронизировать это с докером

2024-06-06 15:49 UTC, budylinr commented on tests/Dockerfile
а что за отдельный Dockerfile в тестах? Лучше тесты гонять в том же окружении, что и продовое

2024-06-06 15:49 UTC, budylinr commented on tests/conftest.py
> +app.state.model = torch_model_load(MODEL_PATH).to(DEVICE)
может app сделать фикстурой тоже?

2024-06-06 15:49 UTC, budylinr commented on tests/test.csv
> +1,circle_1,https://www.avito.ru/
это норм, что урл неверный?

2024-06-06 15:49 UTC, budylinr commented on tests/test_app.py
> +def test_main_page():
хорошо бы делать client фикстурой и добавить в аргументы

2024-06-06 15:49 UTC, budylinr commented on tests/test_app.py
> +@pytest.mark.order(3)
а зачем ты фиксируешь порядок тестов?

2024-06-10 23:56 UTC, Anastasia-Slesarenko commented on load_artifacts/start.py
> +
flake8

2026-07-10 10:38 UTC, closed without merging